package core

import (
	"bytes"
	"context"
	"crypto/ed25519"
	"testing"
	"time"
)

// Test vectors generated by the Python LXMF/RNS reference (gen_vectors.py).
//
// Identity seeds:
//   src: bytes(range(0, 64))   -- first 32 = X25519 prv, last 32 = Ed25519 seed
//   dst: bytes(range(64, 128))
//
// The Ed25519 signing key is the last 32 bytes of the 64-byte identity
// private key. The Ed25519 public key is the last 32 bytes of the 64-byte
// identity public key.

var (
	srcEdSeed = mustHex("202122232425262728292a2b2c2d2e2f303132333435363738393a3b3c3d3e3f")
	srcEdPub  = mustHex("29acbae141bccaf0b22e1a94d34d0bc7361e526d0bfe12c89794bc9322966dd7")
	srcEdPriv = ed25519.NewKeyFromSeed(srcEdSeed)

	srcDestHash = mustHex("fae321c442e3c9bdcd7a3e79d850e03c")
	dstDestHash = mustHex("cf0b2a4a8d2a0b6978b71290da7cc80e")
)

func TestPackPayload(t *testing.T) {
	msg := &LXMessage{
		DestinationHash: dstDestHash,
		SourceHash:      srcDestHash,
		Timestamp:       time.Unix(1700000000, 0),
		Title:           []byte("Test"),
		Content:         []byte("Hello, World!"),
		Fields:          map[any]any{8: []byte("thread_id_here")},
	}

	expected := mustHex("94cb41d954fc40000000c40454657374c40d48656c6c6f2c20576f726c64218108c40e7468726561645f69645f68657265")
	got, err := msg.packPayload()
	if err != nil {
		t.Fatalf("packPayload: %v", err)
	}
	if !bytes.Equal(got, expected) {
		t.Errorf("packPayload mismatch\n  got:  %x\n  want: %x", got, expected)
	}
}

func TestMessageHash(t *testing.T) {
	msg := &LXMessage{
		DestinationHash: dstDestHash,
		SourceHash:      srcDestHash,
		Timestamp:       time.Unix(1700000000, 0),
		Title:           []byte("Test"),
		Content:         []byte("Hello, World!"),
		Fields:          map[any]any{8: []byte("thread_id_here")},
	}

	payload, err := msg.packPayload()
	if err != nil {
		t.Fatalf("packPayload: %v", err)
	}

	expected := mustHex("e51ea8d9b75ab51f7f52a3a6e52f1aa28959cb9e0b4a1ede3095e92a1bf401ff")
	got := msg.computeHash(payload)
	if !bytes.Equal(got, expected) {
		t.Errorf("message hash mismatch\n  got:  %x\n  want: %x", got, expected)
	}
}

func TestSignAndVerify(t *testing.T) {
	msg := &LXMessage{
		DestinationHash: dstDestHash,
		SourceHash:      srcDestHash,
		Timestamp:       time.Unix(1700000000, 0),
		Title:           []byte("Test"),
		Content:         []byte("Hello, World!"),
		Fields:          map[any]any{8: []byte("thread_id_here")},
	}

	err := msg.Sign(context.Background(), srcEdPriv)
	if err != nil {
		t.Fatalf("Sign: %v", err)
	}

	expectedHash := mustHex("e51ea8d9b75ab51f7f52a3a6e52f1aa28959cb9e0b4a1ede3095e92a1bf401ff")
	if !bytes.Equal(msg.Hash, expectedHash) {
		t.Errorf("hash after sign mismatch\n  got:  %x\n  want: %x", msg.Hash, expectedHash)
	}

	expectedSig := mustHex("370e95fdd71d42c30ea50188797d09627ba72f74a281872f2ceeb9ff66d2b5c4f1e533fa360a052fd32afdf18f447fbab0e4c5ee41b0401ed71f82fd5015eb09")
	if !bytes.Equal(msg.Signature, expectedSig) {
		t.Errorf("signature mismatch\n  got:  %x\n  want: %x", msg.Signature, expectedSig)
	}

	if !msg.Verify(ed25519.PublicKey(srcEdPub)) {
		t.Error("Verify returned false for correctly signed message")
	}
}

func TestPackNoStamp(t *testing.T) {
	msg := &LXMessage{
		DestinationHash: dstDestHash,
		SourceHash:      srcDestHash,
		Timestamp:       time.Unix(1700000000, 0),
		Title:           []byte("Test"),
		Content:         []byte("Hello, World!"),
		Fields:          map[any]any{8: []byte("thread_id_here")},
	}

	if err := msg.Sign(context.Background(), srcEdPriv); err != nil {
		t.Fatalf("Sign: %v", err)
	}

	expected := mustHex("cf0b2a4a8d2a0b6978b71290da7cc80efae321c442e3c9bdcd7a3e79d850e03c370e95fdd71d42c30ea50188797d09627ba72f74a281872f2ceeb9ff66d2b5c4f1e533fa360a052fd32afdf18f447fbab0e4c5ee41b0401ed71f82fd5015eb0994cb41d954fc40000000c40454657374c40d48656c6c6f2c20576f726c64218108c40e7468726561645f69645f68657265")
	got, err := msg.Pack()
	if err != nil {
		t.Fatalf("Pack: %v", err)
	}
	if !bytes.Equal(got, expected) {
		t.Errorf("Pack mismatch\n  got:  %x\n  want: %x", got, expected)
	}
}

func TestUnpackNoStamp(t *testing.T) {
	packed := mustHex("cf0b2a4a8d2a0b6978b71290da7cc80efae321c442e3c9bdcd7a3e79d850e03c370e95fdd71d42c30ea50188797d09627ba72f74a281872f2ceeb9ff66d2b5c4f1e533fa360a052fd32afdf18f447fbab0e4c5ee41b0401ed71f82fd5015eb0994cb41d954fc40000000c40454657374c40d48656c6c6f2c20576f726c64218108c40e7468726561645f69645f68657265")

	msg, err := Unpack(packed)
	if err != nil {
		t.Fatalf("Unpack: %v", err)
	}

	expectedHash := mustHex("e51ea8d9b75ab51f7f52a3a6e52f1aa28959cb9e0b4a1ede3095e92a1bf401ff")
	if !bytes.Equal(msg.Hash, expectedHash) {
		t.Errorf("hash mismatch\n  got:  %x\n  want: %x", msg.Hash, expectedHash)
	}

	if !bytes.Equal(msg.DestinationHash, dstDestHash) {
		t.Errorf("dest hash mismatch")
	}
	if !bytes.Equal(msg.SourceHash, srcDestHash) {
		t.Errorf("source hash mismatch")
	}
	if msg.Timestamp.Unix() != 1700000000 {
		t.Errorf("timestamp = %d, want 1700000000", msg.Timestamp.Unix())
	}
	if !bytes.Equal(msg.Content, []byte("Hello, World!")) {
		t.Errorf("content mismatch: %q", msg.Content)
	}
	if len(msg.Stamp) != 0 {
		t.Errorf("stamp should be nil, got %x", msg.Stamp)
	}

	if !msg.Verify(ed25519.PublicKey(srcEdPub)) {
		t.Error("Verify returned false after Unpack")
	}
}

func TestUnpackWithStamp(t *testing.T) {
	// This packed message has a 5-element payload (with stamp).
	packed := mustHex("cf0b2a4a8d2a0b6978b71290da7cc80efae321c442e3c9bdcd7a3e79d850e03c04e1a8b5c4e8c158539371a3502715f20977cc096c2a425b2bb5537ba182ed9052259c65ce0bd189aeab63982e7800f2ede312c65a762645d59e1f5991cec10495cb41d954fc40000000c400c40f5374616d706564206d65737361676580c4201ad13bbeb7ffdd00cc2143a08382a0763966b49930a8475498f9e18c47f721cf")

	msg, err := Unpack(packed)
	if err != nil {
		t.Fatalf("Unpack: %v", err)
	}

	expectedHash := mustHex("2d44d28ae7059f42e80b49ae456e4b1d55adfce523a393e1ddfa6e5a90a4cc22")
	if !bytes.Equal(msg.Hash, expectedHash) {
		t.Errorf("hash mismatch\n  got:  %x\n  want: %x", msg.Hash, expectedHash)
	}

	expectedStamp := mustHex("1ad13bbeb7ffdd00cc2143a08382a0763966b49930a8475498f9e18c47f721cf")
	if !bytes.Equal(msg.Stamp, expectedStamp) {
		t.Errorf("stamp mismatch\n  got:  %x\n  want: %x", msg.Stamp, expectedStamp)
	}

	if !bytes.Equal(msg.Content, []byte("Stamped message")) {
		t.Errorf("content mismatch: %q", msg.Content)
	}

	if !msg.Verify(ed25519.PublicKey(srcEdPub)) {
		t.Error("Verify returned false for stamped message")
	}

	// The hash must match the stamp-stripped payload, not the wire bytes.
	expectedCanonical := mustHex("94cb41d954fc40000000c400c40f5374616d706564206d65737361676580")
	if !bytes.Equal(msg.canonicalPayload, expectedCanonical) {
		t.Errorf("canonical payload mismatch\n  got:  %x\n  want: %x", msg.canonicalPayload, expectedCanonical)
	}
}

func TestPackWithStamp(t *testing.T) {
	// Build a message with a pre-set stamp, sign, and pack.
	// The packed output should include the stamp as the 5th element.
	stamp := mustHex("1ad13bbeb7ffdd00cc2143a08382a0763966b49930a8475498f9e18c47f721cf")

	msg := &LXMessage{
		DestinationHash: dstDestHash,
		SourceHash:      srcDestHash,
		Timestamp:       time.Unix(1700000000, 0),
		Title:           []byte{},
		Content:         []byte("Stamped message"),
		Fields:          make(map[any]any),
		Stamp:           stamp,
	}

	if err := msg.Sign(context.Background(), srcEdPriv); err != nil {
		t.Fatalf("Sign: %v", err)
	}

	expectedSig := mustHex("04e1a8b5c4e8c158539371a3502715f20977cc096c2a425b2bb5537ba182ed9052259c65ce0bd189aeab63982e7800f2ede312c65a762645d59e1f5991cec104")
	if !bytes.Equal(msg.Signature, expectedSig) {
		t.Errorf("signature mismatch\n  got:  %x\n  want: %x", msg.Signature, expectedSig)
	}

	packed, err := msg.Pack()
	if err != nil {
		t.Fatalf("Pack: %v", err)
	}

	expected := mustHex("cf0b2a4a8d2a0b6978b71290da7cc80efae321c442e3c9bdcd7a3e79d850e03c04e1a8b5c4e8c158539371a3502715f20977cc096c2a425b2bb5537ba182ed9052259c65ce0bd189aeab63982e7800f2ede312c65a762645d59e1f5991cec10495cb41d954fc40000000c400c40f5374616d706564206d65737361676580c4201ad13bbeb7ffdd00cc2143a08382a0763966b49930a8475498f9e18c47f721cf")
	if !bytes.Equal(packed, expected) {
		t.Errorf("Pack with stamp mismatch\n  got:  %x\n  want: %x", packed, expected)
	}
}

func TestRoundtrip(t *testing.T) {
	msg := &LXMessage{
		DestinationHash: dstDestHash,
		SourceHash:      srcDestHash,
		Timestamp:       time.Unix(1700000000, 0),
		Title:           []byte("RT"),
		Content:         []byte("roundtrip test"),
		Fields:          make(map[any]any),
	}

	if err := msg.Sign(context.Background(), srcEdPriv); err != nil {
		t.Fatalf("Sign: %v", err)
	}
	packed, err := msg.Pack()
	if err != nil {
		t.Fatalf("Pack: %v", err)
	}

	unpacked, err := Unpack(packed)
	if err != nil {
		t.Fatalf("Unpack: %v", err)
	}

	if !bytes.Equal(unpacked.Hash, msg.Hash) {
		t.Error("hash mismatch after roundtrip")
	}
	if !unpacked.Verify(ed25519.PublicKey(srcEdPub)) {
		t.Error("Verify failed after roundtrip")
	}
	if !bytes.Equal(unpacked.Content, msg.Content) {
		t.Error("content mismatch after roundtrip")
	}
}
