package core

import (
	"bytes"
	"encoding/hex"
	"testing"
)

func mustHex(s string) []byte {
	b, err := hex.DecodeString(s)
	if err != nil {
		panic(err)
	}
	return b
}

// All expected values in this file were generated by the Python LXMF/RNS
// reference implementation (gen_vectors.py).

func TestFullHash(t *testing.T) {
	input := mustHex("68656c6c6f206c786d66") // b"hello lxmf"
	expected := mustHex("4c43d1dca6a11689d4c33620b86605828f6a651e645c2896647f861118deb4d4")
	got := fullHash(input)
	if !bytes.Equal(got, expected) {
		t.Errorf("fullHash mismatch\n  got:  %x\n  want: %x", got, expected)
	}
}

func TestTruncatedHash(t *testing.T) {
	input := mustHex("68656c6c6f206c786d66")
	expected := mustHex("4c43d1dca6a11689d4c33620b8660582")
	got := TruncatedHash(input)
	if !bytes.Equal(got, expected) {
		t.Errorf("TruncatedHash mismatch\n  got:  %x\n  want: %x", got, expected)
	}
}

func TestHKDF(t *testing.T) {
	material := mustHex("746573745f6d6174657269616c5f666f725f686b6466")
	salt := mustHex("f7089d74bf224cc21fb8191bafefe24d80709bf2e598d0e8dd9648e599cfe594")
	expected := mustHex("894d2f520d6aca920542e03cf9623b3a8d6153ba6997d3360842fb4a81eab89c691fe9268279061c51c51691ff434205d94eafa891726be0bbee4ce2b7e1d58f")

	got := hkdf(64, material, salt, nil)
	if !bytes.Equal(got, expected) {
		t.Errorf("hkdf mismatch\n  got:  %x\n  want: %x", got, expected)
	}
}

func TestStampWorkblock(t *testing.T) {
	material := mustHex("a67a5879c32eef0408395f7db5f78c84efe80754fe869caa2c95b2275a162a49")
	expected := mustHex("22aa01e29ab1f555f48674fe4174819fc06143fbf2e9cfe136eaf54ef397babe130f3d9e98a568da719eedaf8cc4c3baa2b143ed00e781b9dea75eea1b7da26ef012397a74c76d934aa957088fc617f05fa6805ba472a6f3a123a4f3aaad84f8a888375637419fc2a01f790318ba1d8b201f005f19bde0585a2f5e293d539d781d14300f4a66569b69bf9d017378d6a1514e3d2116a36c91406a91a0d463b6870c3743ccee3b3320cb16d1af5ff2725849b8a9feb21c9fc31b093af6c8c3074a0d81ced9323b3a35fe6c5a1ad91a752c682a47e58d61561d6c1c68a8df4bac2baadc78ece22ef6a8b6b921a327cb2d6d30f0747aa77f69e5287b90922b30c4e42c9d09e891efe4e4eeaf18328c3a3cdd9fa157543171424f320eaf01accc3980ed5f0357951bab63dcf196ed8b4808fe31c4c413235b3fcfe254a09285543fcd8a02101447475aeea028ce35116c6ded22e2aba742c8ee68797262b7fd7d322629bdee0e0a22669a4c1a4126c19ee6637db69efe4d4df4450549eb66b8bd59023a5d0d591872bb6ec815b87d7fff15c179c023d3ddfd6eb74f2cf3a42a688f9ebbeef5c837edddcacb3705e2149f935506ba99e6de439b98428a45125ce6a23390a5e93c02a668280ef632b6ed9e863853c5b6c864b2ef910f3f6b555c636d9ad0dcff67182311b5d77e0003e40677076a9d388c5fe07cd24a73497bda9b5ca009289da935798572dafe5495d8de6a9c83937f73cb0b5917400a36cb8a2e417f301bb99e181eb0c131d5b38a2701762ee8cb60fa3ed5127c077fcffd17568b9a58562e1de81a587cabe85f3ae413df1645197e9d9b822731dd1b87e4df8ddae43f5e9d3e1405b131640b30895ca353f75fdccdd8658501e51ccf7cbf7dcc05c7122a4eed05e99495c739ad041524b53109c5a6242977cdc70bfccbbe6e43543bc33f146f2e562396acd9ad0f5fa0a4c9e6209293c3322bca2f9960e8e3978e0ebb6efdce7aa14a8b7f9b6c6c4b71428412d55010b792cf4b210f5f26cb0cebd779ec464259b4984994498767d16e83e66ae1c8c95b4596d65ee395cda941d7cf")

	got := StampWorkblock(material, 3)
	if len(got) != 768 {
		t.Fatalf("workblock length = %d, want 768", len(got))
	}
	if !bytes.Equal(got, expected) {
		t.Errorf("StampWorkblock mismatch\n  got:  %x\n  want: %x", got[:64], expected[:64])
	}
}

func TestStampValue(t *testing.T) {
	material := mustHex("a67a5879c32eef0408395f7db5f78c84efe80754fe869caa2c95b2275a162a49")
	wb := StampWorkblock(material, 3)
	stamp := mustHex("000102030405060708090a0b0c0d0e0f101112131415161718191a1b1c1d1e1f")

	// Verify the intermediate hash matches Python.
	combined := append(wb, stamp...)
	resultHash := fullHash(combined)
	expectedHash := mustHex("32af9c08479f121b360de566e14771b17d9c5bbf656a1f6ef52c1b238fa97ac7")
	if !bytes.Equal(resultHash, expectedHash) {
		t.Errorf("result hash mismatch\n  got:  %x\n  want: %x", resultHash, expectedHash)
	}

	got := StampValue(wb, stamp)
	if got != 2 {
		t.Errorf("StampValue = %d, want 2", got)
	}
}

func TestStampValid(t *testing.T) {
	material := mustHex("a67a5879c32eef0408395f7db5f78c84efe80754fe869caa2c95b2275a162a49")
	wb := StampWorkblock(material, 3)
	stamp := mustHex("000102030405060708090a0b0c0d0e0f101112131415161718191a1b1c1d1e1f")

	// The stamp has value=2, so it should be valid at cost 1 and 2, but not 3.
	if !StampValid(stamp, 1, wb) {
		t.Error("StampValid(cost=1) should be true")
	}
	if !StampValid(stamp, 2, wb) {
		t.Error("StampValid(cost=2) should be true")
	}
	if StampValid(stamp, 3, wb) {
		t.Error("StampValid(cost=3) should be false")
	}
}

func TestTicketStamp(t *testing.T) {
	ticket := mustHex("aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa")
	messageID := mustHex("2d44d28ae7059f42e80b49ae456e4b1d55adfce523a393e1ddfa6e5a90a4cc22")
	expected := mustHex("6f08e3d7eef2c2deed3165c4b885547e")

	got := TruncatedHash(append(ticket, messageID...))
	if !bytes.Equal(got, expected) {
		t.Errorf("ticket stamp mismatch\n  got:  %x\n  want: %x", got, expected)
	}
}

func TestValidateStampWithTicket(t *testing.T) {
	ticket := mustHex("aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa")
	messageHash := mustHex("2d44d28ae7059f42e80b49ae456e4b1d55adfce523a393e1ddfa6e5a90a4cc22")
	ticketStamp := mustHex("6f08e3d7eef2c2deed3165c4b885547e")

	msg := &LXMessage{
		Hash:  messageHash,
		Stamp: ticketStamp,
	}

	valid, value := ValidateStamp(msg, 16, [][]byte{ticket})
	if !valid {
		t.Error("ValidateStamp with ticket should return true")
	}
	if value != CostTicket {
		t.Errorf("ValidateStamp value = %d, want %d (CostTicket)", value, CostTicket)
	}
}

func TestValidateStampWithPoW(t *testing.T) {
	messageHash := mustHex("2d44d28ae7059f42e80b49ae456e4b1d55adfce523a393e1ddfa6e5a90a4cc22")
	stamp := mustHex("1ad13bbeb7ffdd00cc2143a08382a0763966b49930a8475498f9e18c47f721cf")

	msg := &LXMessage{
		Hash:  messageHash,
		Stamp: stamp,
	}

	valid, value := ValidateStamp(msg, 1, nil)
	if !valid {
		t.Error("ValidateStamp with PoW stamp should return true at cost=1")
	}
	if value < 1 {
		t.Errorf("stamp value = %d, want >= 1", value)
	}
}
